language: bash
os: linux
sudo: required

services:
  - docker
  
install:
  - sudo apt-get install -y net-tools
  - sudo apt-get install -y bridge-utils
  - sudo ./install_docker_ovs.sh
  - sudo ./load_image.sh
  
before_script:
  - sudo ./start.sh 
 
script:
  - sudo ./test.sh

after_script:
  - sudo ./stop.sh
