language: bash
os: linux
sudo: required

services:
  - docker
  
install:
  - sudo apt-get update && apt-get install -y net-tools
  - ./install_docker_ovs.sh
  - ./load_image.sh
  
before_script:
  - ./start.sh 
 
script:
  - ./test.sh

after_script:
  - ./stop.sh
